name: Build & Deploy page

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Deploy page
    steps:
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v2

      # https://github.com/marketplace/actions/github-pages-action
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./embedded
